services:
  n8n:
    container_name: n8n
    image: paschendale/n8n-geospatial
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5678:5678
    volumes:
      - ./n8n-data:/home/node/.n8n
