name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t paschendale/n8n-geospatial:test . --platform linux/amd64

      - name: Start container for testing
        run: |
          docker run -d --name n8n-test -p 5678:5678 \
            -e N8N_ENCRYPTION_KEY=test-key \
            paschendale/n8n-geospatial:test
          sleep 30  # Wait for n8n to start

      - name: Test QGIS accessibility
        run: |
          docker exec n8n-test qgis --version
          docker exec n8n-test python3 -c "import qgis.core; print('QGIS Python bindings working')"

      - name: Test n8n accessibility
        run: |
          curl -f http://localhost:5678 || exit 1
          echo "n8n is accessible at http://localhost:5678"

      - name: Test GDAL accessibility
        run: |
          docker exec n8n-test gdalinfo --version
          docker exec n8n-test python3 -c "from osgeo import gdal; print('GDAL Python bindings working')"

      - name: Test PDAL accessibility
        run: |
          docker exec n8n-test pdal --version
          docker exec n8n-test python3 -c "import pdal; print('PDAL Python bindings working')"

      - name: Cleanup
        if: always()
        run: |
          docker stop n8n-test || true
          docker rm n8n-test || true

      - name: Push to registry (on main/master)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag paschendale/n8n-geospatial:test paschendale/n8n-geospatial:latest
          docker push paschendale/n8n-geospatial:latest
